name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Start deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/asknt-vue-front-hpace
            chmod +x build.sh
            ./build.sh
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
          port: 2222
